blog:
  title: beet-11ty
  description: 
    metatag: a beginer theme based blog project with 11ty
    logo: beetcabin
    footer: Simply built by beet
  components: 
    nav_items: 
      - home
      - shared
      - tags
    sociallogo: 
      github: https://github.com/beetcb/
      qq: https://qm.qq.com/cgi-bin/qm/qr?k=eaqvtvbTAtD7iw-HXwverJr736BwdPs6&noverify=0
      

link:
  blog: https://www.beetcb.com/
  logo_src: https://www.beetcb.com/pic/logo.svg
  highlight_css: /src/css/prism-duotone-sea.css
  my_css: /src/css/my.css



