blog:
  title: beet-11ty
  description: 
    metatag: a beginer theme based blog project with 11ty
    logo: beet cabin
    footer: Simply built by beet
  components: 
    nav_items: 
      - home
      - shared
      - tags 
    sociallogo: 
      github: https://github.com/beetcb/
      githubBlog: https://github.com/beetcb/beetcb.github.io/
      twitter: https://twitter.com/beetcb1
      zhihu: https://www.zhihu.com/people/ur-apprentice/posts
      wechat: #
      qq: https://qm.qq.com/cgi-bin/qm/qr?k=eaqvtvbTAtD7iw-HXwverJr736BwdPs6&noverify=0
      telegram: #

link:
  blog: https://www.beetcb.com/
  logo_src: /src/beet-logo.png
  highlight_css: /src/css/prism-dracula.css
  my_css: /src/css/my.css



