blog:
  site_name: beet's blog
  url: https://www.beetcb.com/
  title: Beet's blog, a frontEnd lover's blog site
  description:
    header: "<strong>b b</strong><br><small>(🙉 short for beet's blog)</small>"
    metatag: Beet's blog, share & blogging
    keywords: beetcb blog site, beet's blog, frontEnd, beet 的博客, www.beetcb.com, beetcb.com
    footer: made with love&
  components:
    social:
      github: https://github.com/beetcb/beetcb.github.io
      twitter: https://twitter.com/beetcb1
      zhihu: https://www.zhihu.com/people/ur-apprentice/posts
      wechat: #
      qq: https://qm.qq.com/cgi-bin/qm/qr?k=eaqvtvbTAtD7iw-HXwverJr736BwdPs6&noverify=0
      telegram: https://t.me/@beetbeet

link:
  favicon: /static/assets/favicon.ico
  blog: https://www.beetcb.com/
  logo_src: /static/assets/beet-logo.png
  packed_js: /static/main.js
  icon: /static/assets/icon.svg
  css: /static/main.css
  turbolinks: 'https://cdn.jsdelivr.net/npm/turbolinks@5.2.0/dist/turbolinks.min.js'
